"use client";
import { Providers } from "./providers";
import type { Metadata } from "next";
import { usePathname } from "next/navigation";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const showNavbar =
    pathname !== "/auth/login" &&
    pathname !== "/auth/signup" &&
    !pathname.startsWith("/admin");

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {showNavbar && <Navbar />}
          <main className="relative ">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
